# Generated by Django 2.2.16 on 2022-06-09 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20220609_1536'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follow',
            options={'ordering': ['-user']},
        ),
    ]
